# Label for issues related to performance
performance:
  - '(performance|speed|slow|latency|throughput|bandwidth|optimization|optimisation|optimise|optimize)'

# Label for issues related to security
security:
  - '(security|vulnerability|secure|vuln|exploit|exploitable|exploitation|exploited|exploiting|attack|attacker|attacking|attacked|malicious|malware|malicious)'

# Label for issues related to documentation
documentation:
  - '(documentation|docs|doc|readme)'

# Label for issues related to user interface
ui:
  - '(user interface|user experience|graphical user interface|web|website)'

# Label for issues related to bug reports
bug:
  - '(bug|error|issue|problem|fault|defect|flaw|glitch|mistake|incorrect|inaccurate|broken|crash|crashing|crashed|freeze|freezing|frozen|hang|hanging|hung|stuck|unresponsive|unexpected|unintended|unwanted|unintentional|unplanned|unpredictable|unforeseen|unintended|unwanted|unintentional|unplanned|unpredictable|unforeseen|unintended|unwanted|unintentional|unplanned|unpredictable|unforeseen)'

# Label for enhancement requests
enhancement:
  - '(enhancement|improvement|feature|request|suggestion|idea|proposal|enhance|improve|feature|request|suggest|propose)'

# Label for issues marked as 'urgent' or 'critical'
critical:
  - '(critical|urgent|important|severe|serious|grave)'

# Label for issues with golang
golang:
  - '(golang|go|gopher|gophers|golangs|goos|goarch|gobuilt)'

# Label for issues with api
api:
  - '(api|apis)'

# Label for issues with workflow
workflow:
  - '(workflow|workflows)'

# Label for issues with build
build:
  - '(build|builds)'

# Label for issues with testing
testing:
  - '(testing|tests|test)'

# Label for issues with deployment
deployment:
  - '(deployment|deployments|deploy)'

# Label for issues with server
server:
  - '(server|servers|serverless|vm|vms|vps|virtual machine|virtual machines|virtual private server|virtual private servers)'

# Label for issues with web
web:
  - '(web|website|websites|webapp|webapps|web application|web applications)'

# Label for issues with jiotv
jiotv:
  - '(jiotv)'
