name: Test build for PR

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        strategy:
          matrix:
              goos: [linux, windows]
              goarch: [amd64, arm64]
              exclude:
                  - goos: windows
                    goarch: arm64
        steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.21
        - name: Build binary for ${{ matrix.goos }}/${{ matrix.goarch }}
          run: |
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/jiotv_go-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags "-s -w" ./cmd/jiotv_go

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: jiotv_go-${{ matrix.goos }}-${{ matrix.goarch }}
            path: ./bin/

    post_success:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          pull-requests: write
      needs: build
      if: success()
      steps:
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Build was successfull for this PR ✅. [Download binaries](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})

    post_failure:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          pull-requests: write
      needs: build
      if: failure()
      steps:
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Build failed for this PR ❌. [Check logs](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
