name: Check build for Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - "dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build:
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(github.event.head_commit.message, '[release]'))
        permissions:
            contents: read
        runs-on: ubuntu-latest
        strategy:
          matrix:
              goos: [linux, windows]
              goarch: [amd64, arm64]
              exclude:
                  - goos: windows
                    goarch: arm64
        steps:
        - uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.21
        - name: Build binary for ${{ matrix.goos }}/${{ matrix.goarch }}
          run: |
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/jiotv_go-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags "-s -w" ./cmd/jiotv_go

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: jiotv_go-${{ matrix.goos }}-${{ matrix.goarch }}
            path: ./bin/

    post_success:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          pull-requests: write
      needs: build
      if: success() && github.event_name == 'pull_request'
      steps:
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Build was successfull for this PR ✅. [Download binaries](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})

    post_failure:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          pull-requests: write
      needs: build
      if: failure() && github.event_name == 'pull_request'
      steps:
        - name: Comment on PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Build failed for this PR ❌. [Check logs](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})

    post_release:
      runs-on: ubuntu-latest
      needs: build
      # If success and push to dev branch and commit message contains [release]
      if: success() && github.event_name == 'push'
      steps:
        - name: Download binaries
          uses: actions/download-artifact@v2
          with:
            path: ./bin/
        
        - name: Prepare dev tag
          id: prepare_dev_tag
          run: |
            echo "tag=$(date +'dev-v%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
          
        - name: Upload build to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.PAT }}
            file: ./bin/*
            tag: ${{ steps.prepare_dev_tag.outputs.tag }}
            overwrite: false
            file_glob: true
            prerelease: true
            body: |
              This is a dev build. It is only for testing purposes.

